  
@baseUrl = http://localhost:9000
  
GET {{baseUrl}}/todo/64b4e495cb2efff5a5d2a673
  
###

GET {{baseUrl}}/todos 
  
###

POST {{baseUrl}}/todo
content-type: application/json

{
  "todo": {
    "title": "Task 2",
    "description": "Task description 2" 
  }
}
  
###

PUT {{baseUrl}}/todo/64b4e495cb2efff5a5d2a673
content-type: application/json

{
  "todo": {
    "title": "Task [updated]",
    "description": "Task description [updated]"
  }
}
  
###

DELETE {{baseUrl}}/todo/64b4e495cb2efff5a5d2a673
  